get:
  tags:
    - Product
  summary: Get Product by id
  operationId: getProductById
  parameters:
    - name: id
      in: path
      description: The id that needs to be fetched
      required: true
      schema:
        type: string
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                $ref: ../components/schemas/Product.yaml
    '404':
      description: No document found with that id
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
put:
  tags:
    - Product
  summary: Update Product
  description: This can only be done by the admin
  operationId: updateProduct
  parameters:
    - name: id
      in: path
      description: Product that need to be updated
      required: true
      schema:
        type: string
  requestBody:
    description: Updated Product object
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Product.yaml
    required: true
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                $ref: ../components/schemas/Product.yaml
    '400':
      description: Use of active in request or Invalid Input
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
    '404':
      description: No document found with that id
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
delete:
  tags:
    - Product
  summary: (Soft)Delete Product
  description: This can only be done by the admin. Disable a Product
  operationId: deleteProduct
  parameters:
    - name: id
      in: path
      description: The Product that needs to be deleted
      required: true
      schema:
        type: string
  responses:
    '204':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
    '404':
      description: No document found with that id
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
