post:
  tags:
    - Product
  summary: add Product
  operationId: AddProduct
  requestBody:
    description: Creat Product object
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ProductAdd.yaml
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                $ref: ../components/schemas/Product.yaml
    '400':
      description: QR code already in use or Invalid Input
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
    '404':
      description: QR code not found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
