delete:
  tags:
    - Product
  summary: Delete Product
  description: Only possible as admin
  operationId: HardDeleteProduct
  parameters:
    - name: id
      in: path
      description: The Product that needs to be deleted
      required: true
      schema:
        type: string
  responses:
    '204':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
    '404':
      description: No document found with that id
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
