openapi: 3.0.1
info:
  title: STONKS
  description: This is the Stonks (Stocks management application) API
  contact:
    email: leonard.besseau@heig-vd.ch
  version: 1.0.0
tags:
  - name: User
    description: Operations about user
  - name: Element
    description: Operations about element
  - name: Event
    description: Operations about event
  - name: Location
    description: Operations about location
  - name: Product
    description: Operations about product
  - name: QR
    description: Operations about product
paths:
  /users/login:
    $ref: paths/users@login.yaml
  /users/signup:
    $ref: paths/users@signup.yaml
  /users:
    $ref: paths/users@.yaml
  '/users/{id}':
    $ref: 'paths/users@{id}.yaml'
  /elements:
    $ref: paths/elements@.yaml
  '/elements/{id}':
    $ref: 'paths/elements@{id}.yaml'
  '/elements/local/{location}':
    $ref: 'paths/elements@local@{location}.yaml'
  '/elements/move/{id}/{location}':
    $ref: 'paths/elements@move@{id}@{location}.yaml'
  /elements/add:
    $ref: paths/elements@add.yaml
  '/elements/hardDel/{id}':
    $ref: 'paths/elements@hardDel@{id}.yaml'
  /events/connections:
    $ref: paths/events@connections@.yaml
  /events/order:
    $ref: paths/events@order@.yaml
  /events/element:
    $ref: paths/events@element@.yaml
  '/events/connections/{id}':
    $ref: 'paths/events@connections@{id}.yaml'
  '/events/order/{id}':
    $ref: 'paths/events@order@{id}.yaml'
  '/events/element/{id}':
    $ref: 'paths/events@element@{id}.yaml'
  '/events/connections/user/{id}':
    $ref: 'paths/events@connections@user@{id}.yaml'
  '/events/element/user/{id}':
    $ref: 'paths/events@element@user@{id}.yaml'
  '/events/element/product/{id}':
    $ref: 'paths/events@element@product@{id}.yaml'
  '/locations/{id}':
    $ref: 'paths/locations@{id}.yaml'
  /locations:
    $ref: paths/locations@.yaml
  /locations/add:
    $ref: paths/locations@add.yaml
  '/locations/hardDel/{id}':
    $ref: 'paths/locations@hardDel@{id}.yaml'
  '/products/{id}':
    $ref: 'paths/products@{id}.yaml'
  /products:
    $ref: paths/products@.yaml
  /products/add:
    $ref: paths/products@add.yaml
  '/products/hardDel/{id}':
    $ref: 'paths/products@hardDel@{id}.yaml'
  '/QR/{id}':
    $ref: 'paths/QR@{id}.yaml'
  /QR:
    $ref: paths/QR@.yaml
  /QR/add:
    $ref: paths/QR@add.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
servers:
  - url: 'http://127.0.0.1:4000/api/v1'
    description: Dev server (uses test data)
